# Generated by Django 5.0.14 on 2026-06-14 14:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=12, verbose_name='Código')),
                ('atividade', models.TextField(blank=True, verbose_name='Atividade')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Código de Atividade',
                'verbose_name_plural': 'Códigos de Atividade',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CodigoSAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cenario', models.IntegerField(blank=True, null=True, verbose_name='Cenário')),
                ('codigo_atividade', models.CharField(db_index=True, max_length=12, verbose_name='Código atividade')),
                ('codigo_sap', models.CharField(max_length=40, verbose_name='Código SAP')),
                ('aliquota', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Alíquota')),
                ('chave1', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='Chave 1')),
                ('chave2', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='Chave 2')),
            ],
            options={
                'verbose_name': 'Código SAP',
                'verbose_name_plural': 'Códigos SAP',
                'ordering': ['codigo_atividade', 'cenario'],
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=20, verbose_name='Empresa')),
                ('cia', models.CharField(blank=True, max_length=20, verbose_name='CIA')),
                ('planta', models.CharField(max_length=120, verbose_name='Planta')),
                ('municipio', models.CharField(blank=True, max_length=120, verbose_name='Município')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('cep', models.CharField(blank=True, max_length=12, verbose_name='CEP')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
                'ordering': ['planta'],
            },
        ),
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=48, unique=True, verbose_name='Token')),
                ('fornecedor_nome', models.CharField(blank=True, max_length=160, verbose_name='Fornecedor (referência)')),
                ('fornecedor_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do fornecedor')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação interna')),
                ('status', models.CharField(choices=[('pendente', 'Aguardando preenchimento'), ('enviado', 'Cotação enviada')], default='pendente', max_length=12, verbose_name='Status')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('expira_em', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Convite',
                'verbose_name_plural': 'Convites',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fornecimento', models.CharField(choices=[('Serviços', 'Serviços'), ('Mercadoria', 'Mercadoria'), ('Serviços e Mercadoria', 'Serviços e Mercadoria')], max_length=30, verbose_name='Tipo de fornecimento')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nome fantasia')),
                ('regime', models.CharField(choices=[('Simples Nacional', 'Simples Nacional'), ('MEI', 'MEI'), ('Lucro Presumido', 'Lucro Presumido'), ('Lucro Real', 'Lucro Real')], max_length=30, verbose_name='Regime tributário')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=120, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado (UF)')),
                ('cep', models.CharField(blank=True, max_length=12, verbose_name='CEP')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='Telefone / WhatsApp')),
                ('numero_proposta', models.CharField(blank=True, max_length=60, verbose_name='Número da proposta')),
                ('cep_contato', models.CharField(blank=True, max_length=12, verbose_name='CEP (proposta)')),
                ('frete', models.CharField(blank=True, max_length=60, verbose_name='Frete')),
                ('prazo_pagamento', models.CharField(blank=True, max_length=60, verbose_name='Prazo de pagamento')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de emissão')),
                ('total_servico', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_material', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_ipi', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_icms', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_retido', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviada', 'Enviada')], default='enviada', max_length=12, verbose_name='Status')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('convite', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotacao', to='cotacoes.convite')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotacoes.filial', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Cotação',
                'verbose_name_plural': 'Cotações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemMercadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=200, verbose_name='Código ou descrição do item')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Quantidade')),
                ('unidade', models.CharField(blank=True, max_length=20, verbose_name='Unidade de medida')),
                ('prazo_entrega', models.CharField(blank=True, max_length=60, verbose_name='Prazo de entrega')),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='Valor unitário')),
                ('cst_icms', models.CharField(blank=True, max_length=10, verbose_name='CST ICMS')),
                ('cfop', models.CharField(blank=True, max_length=10, verbose_name='CFOP')),
                ('cod_cest', models.CharField(blank=True, max_length=12, verbose_name='COD CEST')),
                ('categoria', models.CharField(blank=True, choices=[('Ativo Fixo', 'Ativo Fixo'), ('Uso ou Consumo', 'Uso ou Consumo'), ('Industrialização', 'Industrialização'), ('Comercialização', 'Comercialização')], max_length=30, verbose_name='Categoria')),
                ('ncm', models.CharField(blank=True, max_length=12, verbose_name='NCM')),
                ('excecao', models.CharField(blank=True, max_length=12, verbose_name='Exceção')),
                ('perc_ipi', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='IPI %')),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Valor IPI')),
                ('perc_icms', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='ICMS %')),
                ('perc_reducao_base', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='% Redução base ICMS')),
                ('base_icms', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Base ICMS')),
                ('valor_icms', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Valor ICMS')),
                ('icms_st', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='ICMS ST')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Valor total')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercadorias', to='cotacoes.cotacao')),
            ],
            options={
                'verbose_name': 'Item de Mercadoria',
                'verbose_name_plural': 'Itens de Mercadoria',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_servico', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Valor do serviço')),
                ('codigo_servico', models.CharField(blank=True, max_length=12, verbose_name='Código do serviço')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('perc_iss', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='% ISS retido')),
                ('perc_inss', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='% INSS retido')),
                ('perc_csrf', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='% CSRF retido')),
                ('perc_irrf', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='% IRRF retido')),
                ('total_retido', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total retido')),
                ('codigo_sap', models.CharField(blank=True, max_length=40, verbose_name='Código SAP')),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Valor líquido')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='cotacoes.cotacao')),
            ],
            options={
                'verbose_name': 'Item de Serviço',
                'verbose_name_plural': 'Itens de Serviço',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
