# Generated by Django 5.0.14 on 2026-06-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='aceite_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aceite em'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='aceite_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do aceite'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='aceite_termos',
            field=models.BooleanField(default=False, verbose_name='Aceitou os termos'),
        ),
    ]
