# Generated by Django 5.0.14 on 2026-06-14 14:57

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0002_cotacao_aceite_em_cotacao_aceite_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(default='Electrolux', max_length=160, verbose_name='Cliente')),
                ('responsavel', models.CharField(blank=True, max_length=160, verbose_name='Responsável')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de contato')),
                ('data_inicio', models.DateField(verbose_name='Início do contrato')),
                ('data_vencimento', models.DateField(verbose_name='Vencimento do contrato')),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor anual (R$)')),
                ('indice_reajuste', models.CharField(default='IPCA', max_length=20, verbose_name='Índice de reajuste')),
                ('dias_alerta', models.PositiveIntegerField(default=30, verbose_name='Alertar com (dias) de antecedência')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Licença',
                'verbose_name_plural': 'Licenças',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ReajusteLicenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data do reajuste')),
                ('percentual', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='% IPCA aplicado')),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor anterior')),
                ('valor_novo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor novo')),
                ('vencimento_anterior', models.DateField(verbose_name='Vencimento anterior')),
                ('vencimento_novo', models.DateField(verbose_name='Vencimento novo')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('licenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reajustes', to='cotacoes.licenca')),
            ],
            options={
                'verbose_name': 'Reajuste de Licença',
                'verbose_name_plural': 'Reajustes de Licença',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
